apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus-demo
spec:
  selector:
    app: prometheus-demo
  ports:
    - port: 8080
      name: web
  type: NodePort
