apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-server
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: prometheus-demo
  endpoints:
    - port: web